/**
 * Copyright Université Lyon 1 / Université Lyon 2 (2009-2012)
 * 
 * <ithaca@liris.cnrs.fr>
 * 
 * This file is part of Visu.
 * 
 * This software is a computer program whose purpose is to provide an
 * enriched videoconference application.
 * 
 * Visu is a free software subjected to a double license.
 * You can redistribute it and/or modify since you respect the terms of either 
 * (at least one of the both license) :
 * - the GNU Lesser General Public License as published by the Free Software Foundation; 
 *   either version 3 of the License, or any later version. 
 * - the CeCILL-C as published by CeCILL; either version 2 of the License, or any later version.
 * 
 * -- GNU LGPL license
 * 
 * Visu is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * Visu is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with Visu.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * -- CeCILL-C license
 * 
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use, 
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info". 
 * 
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability. 
 * 
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or 
 * data to be ensured and,  more generally, to use and operate it in the 
 * same conditions as regards security. 
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 * 
 * -- End of licenses
 */
package com.lyon2.visu.domain.model;

import java.util.List;

public class Activity {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities.id_activity
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private Integer id_activity;
	
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities.id_session
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
	private Integer id_session;
	
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities.title
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities.duration
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private Integer duration;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities.ind
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private Integer ind;

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities.id_activity
     *
     * @param id the value for activities.id_activity
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setId_activity(Integer id_activity) {
        this.id_activity = id_activity;
    }
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities.id_activity
     *
     * @return the value of activities.id_activity
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */	public Integer getId_activity() {
        return id_activity;
    }
	
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities.title
     *
     * @return the value of activities.title
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities.title
     *
     * @param title the value for activities.title
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities.duration
     *
     * @return the value of activities.duration
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public Integer getDuration() {
        return this.duration;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities.duration
     *
     * @param evaltime the value for activities.duration
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities.ind
     *
     * @return the value of activities.ind
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public Integer getInd() {
        return this.ind;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities.ind
     *
     * @param order the value for activities.ind
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setInd(Integer ind) {
        this.ind = ind;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities.id_session
     *
     * @return the value of activities.id_session
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public Integer getId_session() {
        return this.id_session;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities.id_session
     *
     * @param session_id the value for activities.id_session
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setId_session(Integer id_session) {
        this.id_session = id_session;
    }

    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() 
    {
        StringBuffer out = new StringBuffer("class Activity ");
        out.append("id_activity = " + this.id_activity + ", ");
		out.append("id_session = " + this.id_session + ", ");
        out.append("title = " + this.title + ", ");
        out.append("duration = " + this.duration + ",");
        out.append("ind = " + this.ind + ", ");
        return out.toString();
    }

    public Activity cloneMe(int idSession)
    {
    	Activity activity = new Activity();
    	activity.setDuration(this.duration);
    	activity.setId_activity(0);
    	activity.setId_session(idSession);
    	activity.setInd(this.ind);
    	activity.setTitle(this.title);
    	return activity;
    }
    
}
