/**
 * Copyright Université Lyon 1 / Université Lyon 2 (2009-2012)
 * 
 * <ithaca@liris.cnrs.fr>
 * 
 * This file is part of Visu.
 * 
 * This software is a computer program whose purpose is to provide an
 * enriched videoconference application.
 * 
 * Visu is a free software subjected to a double license.
 * You can redistribute it and/or modify since you respect the terms of either 
 * (at least one of the both license) :
 * - the GNU Lesser General Public License as published by the Free Software Foundation; 
 *   either version 3 of the License, or any later version. 
 * - the CeCILL-C as published by CeCILL; either version 2 of the License, or any later version.
 * 
 * -- GNU LGPL license
 * 
 * Visu is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * Visu is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with Visu.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * -- CeCILL-C license
 * 
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use, 
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info". 
 * 
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability. 
 * 
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or 
 * data to be ensured and,  more generally, to use and operate it in the 
 * same conditions as regards security. 
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 * 
 * -- End of licenses
 */
package com.lyon2.visu.domain.model;


public class ActivityElement {
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities_elements.id_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
	private Integer id_element;
	
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities_elements.id_activity
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private Integer id_activity;
	
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities_elements.data
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private String data;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities_elements.url_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private String url_element;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities_elements.type_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private String type_element;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activities_elements.type_mime
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private String type_mime;
	
	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities_elements.id_element
     *
     * @return the value of activities_elements.id_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    private int order_activity_element;
    
    
    
    
    
    public Integer getId_element() {
        return id_element;
    }
	
    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities_elements.id_element
     *
     * @param session_id the value for activities_elements.id_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setId_element(Integer id_element) {
        this.id_element = id_element;
    }
	
    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities_elements.id_activity
     *
     * @param id the value for activities_elements.id_activity
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setId_activity(Integer id_activity) {
        this.id_activity = id_activity;
    }
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities_elements.id_activity
     *
     * @return the value of activities_elements.id_activity
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */	public Integer getId_activity() {
        return id_activity;
    }
	
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities_elements.data
     *
     * @return the value of activities_elements.data
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities_elements.data
     *
     * @param title the value for activities_elements.data
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities_elements.url_element
     *
     * @return the value of activities_elements.url_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public String getUrl_element() {
        return url_element;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities_elements.url_element
     *
     * @param evaltime the value for activities_elements.url_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setUrl_element(String url_element) {
        this.url_element = url_element;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities_elements.type_element
     *
     * @return the value of activities_elements.type_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public String getType_element() {
        return type_element;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities_elements.type_element
     *
     * @param order the value for activities_elements.type_element
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setType_element(String type_element) {
        this.type_element = type_element;
    }

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activities_elements.type_mime
     *
     * @return the value of activities_elements.type_mime
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public String getType_mime() {
        return type_mime;
    }
	
    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activities_elements.type_mime
     *
     * @param order the value for activities_elements.type_mime
     *
     * @abatorgenerated Tue May 26 16:38:12 CEST 2009
     */
    public void setType_mime(String type_mime) {
        this.type_mime = type_mime;
    }
    
    public int getOrder_activity_element() {
        return this.order_activity_element;
    }
    public void setOrder_activity_element(int order_activity_element) {
        this.order_activity_element = order_activity_element;
    }
    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() 
    {
        StringBuffer out = new StringBuffer("class Activity ");
        out.append("id_element = " + this.id_element + ", ");
		out.append("id_activity = " + this.id_activity + ", ");
        out.append("data = " + this.data + ", ");
        out.append("url_element = " + this.url_element + ",");
        out.append("type_element = " + this.type_element + ", ");
		out.append("type_mime = " + this.type_mime + ", ");
		out.append("order_activity_element = " + this.order_activity_element + ", ");
        return out.toString();
    }

    public ActivityElement cloneMe(int id_activity)
    {
    	ActivityElement activityElement = new ActivityElement();
    	activityElement.setData(this.data);
    	activityElement.setId_activity(id_activity);
    	activityElement.setId_element(0);
    	activityElement.setOrder_activity_element(this.order_activity_element);
    	activityElement.setType_element(this.type_element);
    	activityElement.setType_mime(this.type_mime);
    	activityElement.setUrl_element(this.url_element);
    	return activityElement;
    }
    
}
